# Rename this file to languages.toml to enable multilingual support
[en]
    languageName = "English"
    languagedirection = "ltr"
    title        = "Mark's Hugo Blog"
    weight       = 1

    [en.params.sidebar]
        subtitle = "Mark's HUGO Blog"

[zh]
    languageName = "简体中文"
    title        = "峰风的技术博客"
    weight       = 2

    [zh.params.sidebar]
        subtitle = "峰风的HUGO技术博客"

[ja]
    languageName = "日本語"
    title        = "Markのブログ"
    weight       = 4

    [ja.params.sidebar]
        subtitle = "Markの技術ブログ"
